travis:
  secure:
    BINSTAR_TOKEN: tfM3wfDnvneiD35royiKhJtKqYaxKVOp3qOaJp42LVaQ+wR6gAAIFZ7HJBRbl4Oq6Eax6ZMCZ/o4l6EddYIW8+Mw4Jh3G4FQ9hP5RTckTvgcUkxFPmxjdnkhYdOw5w+IFisC9yL/ruOytXfNnwAPNSohY6GB83pooSagFjad1k76YgS48RQlnIIFu8OE+Zb+8OfOdtlNwxddL25pLSn3149nCQKnRav70LQc8pYyQuRr7+hEnAVZWPODcoh+1IbVnCyiQMyV1N5OKlt8ZaPZ4SwcxOdNLdcClD+Gn2/LRLgDtFWUlTEFLTHKzCQnROjhEbMcEY33shIE6Py6lBjNlKx2MG6jAXBC2Y6tOHfDotR0CvwltoA0n623ItsubHSRMZ2iknuyKcFFZCP/Ychl1z8/7uz2BD+V8R53kGovfSeckVRAmaKII2mkiKHHQwLZiFXXCA0MdcRBmAWjlC18IXS8SHXh5QEplYQkyhjcXqDp+GOxI/LqkcqyLN7jHBnKP+Ag+TRPXqOM21kMlWxfRADkHk/tvfbr9WRUrcJBRyKGrg2xqc7cXckGb/vCv5H0hUhVFTbFX3wliZyualVk0bBs4bkxJcKENNXim2m0Ih5g7m+ChF3Dfv1XcDpfGAorLE4GGjR2sruxAZZWvi/O9UtMCzTW/r8BT6ZbG1d0qcA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
